name: CI

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

defaults:
  run:
    shell: bash

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    name: 'Lint/Format/Typecheck'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup bun 🍞
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install Dependencies
        run: bun install

      - name: Lint
        run: bun lint

      - name: Format
        run: bun format

      - name: Typecheck
        run: bun typecheck