name: Deploy to Railway

on:
  push:
    branches: [main]

defaults:
  run:
    shell: bash

env:
  CI: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - run: npm install --global @railway/cli@latest

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
