name: Deploy to Railway

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

env:
  CI: true
  ACTIONS_RUNNER_DEBUG: true

jobs:
  deploy:
    name: 'Deploy to railway.app'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint & Format
        run: |
          pnpm lint
          pnpm format

      - name: Install Railway CLI
        run: npm install --global @railway/cli@latest

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up

      - name: Notify Discord
        if: ${{ failure() }}
        env:
          AVATAR_URL: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
        run: |
          curl \
            --request 'POST' \
            --header 'Content-Type: application/json' \
            --form 'payload_json={ \
                "username": "GitHub Actions", \
                "avatar_url": "${AVATAR_URL}", \
                "content": "Deployment to Railway failed" \
              }' \
            --form 'file1=@./railway.txt'
            ${{ secrets.DISCORD_WEBHOOK_URL }}